version: '3'

services:
    php-apache:
      container_name: php-apache
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - db
      ports:
        - '8080:80'
      volumes:
        - ./src:/var/www/html/
    db:
      container_name: mysql
      image: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: 1234
        MYSQL_DATABASE: test_db
        MYSQL_USER: shewa
        MYSQL_PASSWORD: 1234
      ports:
        - "9906:3306"
    phpmyadmin:
      image: phpmyadmin
      restart: always
      ports:
        - 7000:80
      environment:
        - PMA_HOST=db
      depends_on:
        - db